const assert=require('node:assert/strict');
const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
const root=path.resolve(__dirname,'..'),db=require(root+'/miniprogram/data/places');
let page,time=0,next=1;const timers=new Map();
const wx={getWindowInfo:()=>({windowWidth:390,windowHeight:844,statusBarHeight:24}),getStorageSync:()=>[],showShareMenu(){},createSelectorQuery(){let cb;return {in(){return this},select(){return this},boundingClientRect(f){cb=f;return this},exec(){cb({left:0,top:180,width:390,height:460})}}}};
vm.runInNewContext(fs.readFileSync(root+'/miniprogram/pages/map/index.js','utf8'),{require:id=>require(path.resolve(root,'miniprogram/pages/map',id)),Page:p=>page=p,wx,Date:{now:()=>time},setTimeout(fn,delay){const id=next++;timers.set(id,{fn,at:time+delay});return id;},clearTimeout:id=>timers.delete(id)});
page.setData=(p,cb)=>{Object.assign(page.data,p);if(cb)cb();};
function advance(ms){const end=time+ms;while(true){const due=[...timers].filter(([,t])=>t.at<=end).sort((a,b)=>a[1].at-b[1].at)[0];if(!due)break;time=due[1].at;timers.delete(due[0]);due[1].fn();for(const pin of page.data.renderedPlaces){assert.ok(Math.abs(pin.screenX-page.data.mapX-pin.x/100*600*page.data.scale)<1e-8);assert.ok(Math.abs(pin.screenY-page.data.mapY-pin.y/100*579*page.data.scale)<1e-8);}}time=end;}
page.onLoad({});page.onReady();
const start=page.data.mapX;page.selectId('library');assert.equal(page.data.mapX,start);assert.equal(page.data.cameraMoving,true);
advance(112);assert.notEqual(page.data.mapX,start);assert.equal(page.data.cameraMoving,true);
page.selectMapPlace({currentTarget:{dataset:{id:'residence-12'}}});advance(300);
assert.equal(page.data.cameraMoving,false);const pin=page.data.renderedPlaces.find(p=>p.id==='residence-12');assert.equal(pin.screenX,195);assert.equal(pin.screenY,230);
page.zoomIn();advance(80);const interrupted=page.data.mapX;page.onMapTouchStart({touches:[{clientX:160,clientY:300}]});assert.equal(page.data.mapX,interrupted);
page.onMapTouchMove({touches:[{clientX:185,clientY:310}]});advance(400);assert.equal(page.data.mapX,interrupted+25);assert.equal(timers.size,0);
page.onMapTouchEnd({touches:[]});page.zoomOut();assert.ok(timers.size>0);page.onUnload();assert.equal(timers.size,0);
console.log('PASS: intermediate motion frames, artwork/pin alignment, interrupted selection, exact final center, drag takeover, timer cleanup');
advance(400);page.selectId('library');advance(80);
const cameraBeforeDismiss={x:page.data.mapX,y:page.data.mapY,scale:page.data.scale};
page.dismissMapPreview();advance(400);
assert.equal(page.data.selected,null);assert.equal(page.data.related.length,0);
assert.deepEqual({x:page.data.mapX,y:page.data.mapY,scale:page.data.scale},cameraBeforeDismiss);
page.selectMapPlace({currentTarget:{dataset:{id:'residence-12'}}});advance(300);
page.dismissMapPreview();assert.equal(page.data.expandedBuildingId,null);assert.equal(page.data.mapServicePopup,null);
page.selectId('library');advance(300);
page.onMapTouchStart({touches:[{clientX:100,clientY:300}]});
page.onMapTouchMove({touches:[{clientX:150,clientY:310}]});page.onMapTouchEnd({touches:[]});
page.dismissMapPreview();assert.equal(page.data.selected.id,'library');
advance(400);page.dismissMapPreview();assert.equal(page.data.selected,null);
let pending;const originalLayout=page.afterMapLayout;page.afterMapLayout=cb=>{pending=cb;};
page.selectId('library');const staleCenter=pending;page.dismissMapPreview();
const dismissedX=page.data.mapX;staleCenter({left:0,top:180,width:390,height:460});advance(400);
assert.equal(page.data.selected,null);assert.equal(page.data.mapX,dismissedX);assert.equal(timers.size,0);
page.afterMapLayout=originalLayout;
console.log('PASS: blank tap dismisses details and service menu, preserves camera, ignores drag taps and invalidates pending centering');
